# serverless.yml

service: my-express-application

plugins:
 - serverless-apigw-binary

custom:
  apigwBinary:
    types:           #list of mime-types
      - '*/*'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  app:
    handler: lambda.express
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'